/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.asnworks.projects.practice.crunchexamples.domain;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SalesProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SalesProtocol\",\"namespace\":\"org.asnworks.projects.practice.crunchexamples.domain\",\"types\":[{\"type\":\"record\",\"name\":\"Sales\",\"fields\":[{\"name\":\"transactionDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"price\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"paymentType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"state\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"country\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"accountCreated\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastLogin\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"latitude\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"longitude\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SalesProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = org.asnworks.projects.practice.crunchexamples.domain.SalesProtocol.PROTOCOL;
  }
}