/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.asnworks.projects.practice.crunchexamples.domain;

@SuppressWarnings("all")
/** * Define a protocol, the protocol is like a contract(interface). */
@org.apache.avro.specific.AvroGenerated
public interface SongProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SongProtocol\",\"namespace\":\"org.asnworks.projects.practice.crunchexamples.domain\",\"doc\":\"* Define a protocol, the protocol is like a contract(interface).\",\"types\":[{\"type\":\"record\",\"name\":\"Song\",\"doc\":\"* Record corresponds to a class name in Java.\",\"fields\":[{\"name\":\"songId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"* An id given to the song\"},{\"name\":\"songTitle\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"* The name of the song\"},{\"name\":\"artistName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"* The name of the artist the song belongs to\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  /** * Define a protocol, the protocol is like a contract(interface). */
  public interface Callback extends SongProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = org.asnworks.projects.practice.crunchexamples.domain.SongProtocol.PROTOCOL;
  }
}